// Code generated by "stringer -type=OpCode"; DO NOT EDIT

package kclient

import "fmt"

const _OpCode_name = "AddUpdateDeleteIdle"

var _OpCode_index = [...]uint8{0, 3, 9, 15, 19}

func (i OpCode) String() string {
	if i < 0 || i >= OpCode(len(_OpCode_index)-1) {
		return fmt.Sprintf("OpCode(%d)", i)
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
