// Code generated by "stringer -type=Kind"; DO NOT EDIT.
package systemctl

import "fmt"

const _UnitFileCmd_name = "EnableDislableReenable"

var _UnitFileCmd_index = [...]uint8{0, 5, 9, 14, 20}

func (i UnitFileCmd) String() string {
	if i < 0 || i >= UnitFileCmd(len(_UnitFileCmd_index)-1) {
		return fmt.Sprintf("UnitFileCmd(%d)", i)
	}
	return _UnitFileCmd_name[_UnitFileCmd_index[i]:_UnitFileCmd_index[i+1]]
}
