// Code generated by "stringer -type=Kind"; DO NOT EDIT.
package systemctl

import "fmt"

const _UnitCmd_name = "StartStopReloadRestart"

var _UnitCmd_index = [...]uint8{0, 5, 9, 14, 20}

func (i UnitCmd) String() string {
	if i < 0 || i >= UnitCmd(len(_UnitCmd_index)-1) {
		return fmt.Sprintf("UnitCmd(%d)", i)
	}
	return _UnitCmd_name[_UnitCmd_index[i]:_UnitCmd_index[i+1]]
}
