// Code generated by "stringer -type=UnitFileCmd"; DO NOT EDIT.

package systemctl

import "strconv"

const _UnitFileCmd_name = "EnableDisableReenable"

var _UnitFileCmd_index = [...]uint8{0, 6, 13, 21}

func (i UnitFileCmd) String() string {
	if i < 0 || i >= UnitFileCmd(len(_UnitFileCmd_index)-1) {
		return "UnitFileCmd(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UnitFileCmd_name[_UnitFileCmd_index[i]:_UnitFileCmd_index[i+1]]
}
